### PR TITLE
fixed user creation if user is not around

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
I confirmed that this worked.  You can also re-run it and it will regenerate your password.

**Comment by erasche** [comment]
@nathandunn looks great, thank you!

**Comment by nathandunn** [comment]
Yeah, something isn't quite right still.  It never actually creates a user . . .. I'm trying to see why.   This propagates the error to the Apollo create_organism (which is a new, but different error).   I'm not seeing problems with JBrowse anymore though (so that's good).

**Comment by nathandunn** [comment]
Actually this is the error I'm getting: 

```
Return data: {u'error': u'Failed to add the user Cannot access first() element from an empty Iterable'}
```

That is on the Apollo side.  Taking a look.

**Comment by nathandunn** [comment]
The problem is that we are are checking organism permissions when adding a user . . which errors out if there are no organisms.  

I'd fixed this on most cases, but have not fixed it in this one use-case.  Fixing now.

**Comment by nathandunn** [comment]
I'll rebuild / push and let you know.   Getting there.

**Pull request merged**
